### PR TITLE
Use BookInfoAcctivity wherever possible

### PR DESCRIPTION
**Pull request by AY-Chen**
Changed the the views to be swappable depending on "who" is viewing it 

Changed borrower book search to use book info
Changed request list to show book info 
Changed notifications to link to book info(not tested)

### CODE REVIEW

**Comment by Kaho-Lee** [comment]
Could we do some refactoring on borrower section in this PR, which could make @siyuamymi 's PR conflicts solved easily. Because of the sliding windows in borrower page in Amy's PR, the BorrwerPageFragment has already been renamed to BorrowerRequestsFragment. And its related layout, fragment_borrower_page, is renamed to fragment_borrower_requests.

**Comment by AY-Chen** [comment]
> 
> 
> Could we do some refactoring on borrower section in this PR, which could make @siyuamymi 's PR conflicts solved easily. Because of the sliding windows in borrower page in Amy's PR, the BorrwerPageFragment has already been renamed to BorrowerRequestsFragment. And its related layout, fragment_borrower_page, is renamed to fragment_borrower_requests.

In that case hold off on merging this until her PR goes through, then i'll merge the changes from master and fix any issues with that.

**Comment by Kaho-Lee** [comment]
There would be similar activity life cycle problem @MarcusBoay mentioned yesterday.

 Process: com.example.atheneum, PID: 11309
    java.lang.IllegalStateException: Fragment BorrowerPageFragment{14b69ff} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
        at android.support.v4.app.Fragment.getResources(Fragment.java:760)
        at android.support.v4.app.Fragment.getString(Fragment.java:782)
        at com.example.atheneum.fragments.BorrowerPageFragment$4.onDataChange(BorrowerPageFragment.java:169)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by siyuamymi** [comment]
I've fixed borrowing and returning, thanks for waiting! ^^ Can someone please take a look at #182

**Comment by AY-Chen** [comment]
I haven't been able to recreate the crash. Even marcus's crash. Does someone have specific instructions that consistently trigger it to happen? @Kaho-Lee @MarcusBoay

**Comment by siyuamymi** [comment]
@AY-Chen Accepting a book request has been crashing for me everytime, maybe try that?

**Comment by AY-Chen** [comment]
Hm I haven't tested that. But i think the error that @Kaho-Lee and @MarcusBoay weere getting is from an adapter listener crash. Whoever wrote the adapter for the requests(on the borrower page) is not because of the context dying, it's because requesting the book is attempting to update the list of requests when the fragment isn't active. This means that the adapter is still listening when it's not supposed to be.

**Comment by siyuamymi** [comment]
For reference, this was the error that I kept getting: 

 Process: com.example.atheneum, PID: 20885
    java.lang.IllegalStateException: Fragment BorrowerRequestsFragment{a35ac19} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:696)
        at android.support.v4.app.Fragment.getResources(Fragment.java:760)
        at android.support.v4.app.Fragment.getString(Fragment.java:782)
        at com.example.atheneum.fragments.BorrowerRequestsFragment$4.onDataChange(BorrowerRequestsFragment.java:205)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@16.0.6:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@16.0.6:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@16.0.6:55)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6688)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by AY-Chen** [comment]
DO NOT MERGE RIGHT NOW, need to test and make sure i didn't break everything with the new stuff from master

**Pull request merged**
