### PR TITLE
Receive push notifications

### PR DESCRIPTION
**Pull request by MarcusBoay**
Related #26 

The is a WIP implementation. Currently able to receive push notifications from firebase console.

An FCM registration token is stored the database when the user signs in. This is used to reference which device to send notifications to.

How to test it:
1. Go to firebase console
2. Go to "Grow" in sidebar
3. Go to "Cloud messaging"
4. Create a new notification
5. Enter notification text and test on device
6. FCM registration token can be found in the database under "userDeviceTokens"

### CODE REVIEW

**Comment by MarcusBoay** [comment]
I'm not too sure how sending notifications from the application would work yet, which is why I'm separating receiving notifications and sending notifications into separate PRs.

**Comment by ishchow** [comment]
notification:
	userID:
		notificationID:
			notificationID: "
			message: "message"

**Comment by ishchow** [comment]
@MarcusBoay you still wanna merge this?

**Comment by MarcusBoay** [comment]
@ishchow yeah sure

**Pull request merged**
