### PR TITLE
add a new request without search book functionality

### PR DESCRIPTION
**Pull request by Kaho-Lee**
Search functionality is needed before completing issue"04.01.01"

The search book function and the filter of book status should be added before completing this issue. Because the requested book UUID and status check is required for constructing a new request.

Or do you have any idea to get around this problem for project Part4?

@ishchow Could you give me access to log into Firebase to check if a new data is updated properly?

### CODE REVIEW

**Comment by ishchow** [comment]
@Kaho-Lee If you look in our slack page, I pinned a post that had the email and password of cmput301w19t11@gmail.com, which is the account I signed up our team for Firebase. You should be able to sign in and view the Firebase console for our app using those credentials

**Comment by Kaho-Lee** [comment]
> @Kaho-Lee If you look in our slack page, I pinned a post that had the email and password of [cmput301w19t11@gmail.com](mailto:cmput301w19t11@gmail.com), which is the account I signed up our team for Firebase. You should be able to sign in and view the Firebase console for our app using those credentials

Thanks!

**Comment by ishchow** [comment]
@Kaho-Lee 

So you don't need searching of books to be able to complete this issue. You don't even need to be able to view a book to test the base functionality of requests.

Just add a single test book to the database and just start with making requests on this test book. You could upload the book to Firebase in the MainActivity onCreate() method.

The floating action bar on the BorrowerFragment should spawn a NewRequest fragment with the bookID of the test book passed into it. 

When you design your NewRequest fragment, fill in all the information necessary for a request and just send it to the correct database table and verify that the information contained within the database table is correct. Then, you will know that the NewRequest functionality is working.

Does that make sense?

**Comment by Kaho-Lee** [comment]
> @Kaho-Lee
> 
> So you don't need searching of books to be able to complete this issue. You don't even need to be able to view a book to test the base functionality of requests.
> 
> Just add a single test book to the database and just start with making requests on this test book. You could upload the book to Firebase in the MainActivity onCreate() method.
> 
> The floating action bar on the BorrowerFragment should spawn a NewRequest fragment with the bookID of the test book passed into it.
> 
> When you design your NewRequest fragment, fill in all the information necessary for a request and just send it to the correct database table and verify that the information contained within the database table is correct. Then, you will know that the NewRequest functionality is working.
> 
> Does that make sense?

Sounds good.

**Pull request merged**
