### PR TITLE
Add borrower collection

### PR DESCRIPTION
**Pull request by siyuamymi**
added BorrowerCollection and BorrowerCollectionTest

### CODE REVIEW

**Comment by ishchow** [comment]
@siyuamymi 

Why did you remove the blank constructor for User? That constructor is necessary for Firebase to parse the User class. It was used in other unit tests as well. That's probably what is causing the merge conflicts. 

You can try reverting your [first commit](https://github.com/CMPUT301W19T11/Atheneum/pull/36/commits/0f3dedadbc5219363ed9b7757601ede6fdc5d46b). Run this in the Atheneum repository to revert the commit and fix your conflict and push your changes to this PR.

`git revert 0f3dedadbc5219363ed9b7757601ede6fdc5d46b && git push`

What this does is create a new commit that reverses the first commit in this PR (which has the SHA1 hash of 0f3dedadbc5219363ed9b7757601ede6fdc5d46b) and then pushes this change to your remote branch add_borrowerCollection. Your PR will be updated when the remote branch is updated on the server.

**Comment by AY-Chen** [comment]
Also your copyright doesn't have the year and stuff filled in

**Comment by ishchow** [comment]
It looks like since you edited the User class and that was different than what Jiahao just merged, that caued the conflict. You can fix it if you fix the conflicts in the web editor:

image

Personally, I would also change it so that the username and phone number are set to empty strings instead of "user" and "911". I don't think having 911 be a default phone number would make in a real world context, would lead to some chaos at police stations ;).

**Comment by ishchow** [comment]
If you delete this:
```
=======
    public User(){}
>>>>> master
```

and the top part:
`<<<<<<< add_borrowerCollection`

That should fix the conflicts.

**Comment by siyuamymi** [comment]
I deleted my blank constructor because I was anticipating that Jiahao would add it. But I will fix the conflict now.

**Comment by siyuamymi** [comment]
Also Ill change the copyright too.

**Comment by siyuamymi** [comment]
Thanks Isshat and Alex for checking it over ^^

**Pull request merged**
