### PR TITLE
Rmrating and Add Null check in OwnerPageFragment

### LINKED ISSUE #184: Remove owner and borrower ratings from the UI
Don't change the model or the database for this.

### PR DESCRIPTION
**Pull request by samjwu**
Closes #184 
gets rid of ratings in view user profile UI

also add null check to OwnerPageFragment
Null pointer exception occurs if user has no books owned

### CODE REVIEW

**Comment by Kaho-Lee** [comment]
The change is working properly. Thanks for figuring out the null error.

**Comment by ishchow** [comment]
@samjwu Why comment the stuff out? Why not just delete it?

**Comment by samjwu** [comment]
in case we still wanted it or something. there's no compelling reason

**Comment by ishchow** [comment]
@samjwu Fair enough.

**Pull request merged**
