### PR TITLE
Jiahao

### PR DESCRIPTION
**Pull request by Kaho-Lee**
finish use case 04.02.01

### CODE REVIEW

**Comment by MarcusBoay** [comment]
The list itself seems functional and pulls data from the database.

**Comment by Kaho-Lee** [comment]
> The list itself seems functional and pulls data from the database. We might want to use a FirebaseRecyclerAdapter in the future but I'm not too sure.

Thanks. I also see the same ArrayAdapter used in SearchFragment.  I am not sure if there is any difference between this two kinds of adapter either.

**Comment by ishchow** [comment]
I tested this and this isn't working for me. I'm seeing new requests in Firebase but not in the screen.

@Kaho-Lee FirebaseRecyclerView Adapter is better since all you have to do is give it a query and it will automatically pull the data from firebase without you having to manually add a ValueEventListener. Also, FirebaseRecyclerView Adapter has the ability to listen for changes to the requests themselves since it uses a ChildEventListener internally. The ValueEventListener in your array adapter can only check if new requests are added but if you need to check if the requests (ie. their status ) themselves change then it would be better to use FirebaseRecyclerView Adapter.

**Comment by ishchow** [comment]
I think Sam had to use a custom ArrayAdapter since he had to constantly change what he was querying which the FirebaseRecyclerViewAdapter doensn't let you do.

**Comment by Kaho-Lee** [comment]
> I think Sam had to use a custom ArrayAdapter since he had to constantly change what he was querying which the FirebaseRecyclerViewAdapter doensn't let you do.

Thanks! Displaying bugs fixed. And this part should be working properly.

For the adapter issue, requestCollection have a different structure than the ownerCollection. Query should look at the current user in requestCollection first and then go to books section in firebase based on UUID. A custom adapter might be needed. I would continue work on the search part first, and then go back to this to check if there is any possibility to change this part to FirebaseRecyclerViewAdapter.

**Pull request merged**
